// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SampleAnalysisTracking.Data;

#nullable disable

namespace SampleAnalysisTracking.Migrations
{
    [DbContext(typeof(SampleAnalysisTrackingDbContext))]
    [Migration("20260902115108_AddKnowledgeDocumentSourceStatus")]
    partial class AddKnowledgeDocumentSourceStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("analysis_codes", (string)null);
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("default_unit");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("ReferenceMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reference_max");

                    b.Property<decimal?>("ReferenceMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reference_min");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisCodeId", "Code")
                        .IsUnique();

                    b.ToTable("analysis_parameters", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_parameters_reference_range", "\"reference_min\" IS NULL OR \"reference_max\" IS NULL OR \"reference_min\" <= \"reference_max\"");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisParameterId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_parameter_id");

                    b.Property<long?>("EnteredById")
                        .HasColumnType("bigint")
                        .HasColumnName("entered_by");

                    b.Property<DateTimeOffset>("MeasuredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("numeric_value");

                    b.Property<decimal?>("ReferenceMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reference_max");

                    b.Property<decimal?>("ReferenceMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reference_min");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("result_note");

                    b.Property<long>("SampleAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_analysis_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisParameterId");

                    b.HasIndex("EnteredById");

                    b.HasIndex("SampleAnalysisId", "AnalysisParameterId")
                        .IsUnique();

                    b.ToTable("analysis_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_analysis_results_reference_range", "\"reference_min\" IS NULL OR \"reference_max\" IS NULL OR \"reference_min\" <= \"reference_max\"");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "\"role\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<long>("KnowledgeDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_document_id");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("SourceStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("source_status");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<long>("UploadedById")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.HasIndex("IsActive", "Category");

                    b.ToTable("knowledge_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_documents_category", "\"category\" IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_knowledge_documents_source_status", "\"source_status\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeDocumentAnalysisCode", b =>
                {
                    b.Property<long>("KnowledgeDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("knowledge_document_id");

                    b.Property<long>("AnalysisCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_code_id");

                    b.HasKey("KnowledgeDocumentId", "AnalysisCodeId");

                    b.HasIndex("AnalysisCodeId");

                    b.ToTable("knowledge_document_analysis_codes", (string)null);
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedToId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_to");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<string>("SampleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sample_code");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sample_type");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("SampleCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("samples", null, t =>
                        {
                            t.HasCheckConstraint("ck_samples_status", "\"status\" IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnalysisCodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("analysis_code_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long?>("CompletedById")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("RequestedById")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("result_note");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long?>("StartedById")
                        .HasColumnType("bigint")
                        .HasColumnName("started_by");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisCodeId");

                    b.HasIndex("CompletedById");

                    b.HasIndex("RequestedById");

                    b.HasIndex("StartedById");

                    b.HasIndex("Status");

                    b.HasIndex("SampleId", "AnalysisCodeId")
                        .IsUnique();

                    b.ToTable("sample_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_sample_analyses_status", "\"status\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleAnalysisHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ChangedById")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("integer")
                        .HasColumnName("old_status");

                    b.Property<long>("SampleAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_analysis_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("SampleAnalysisId", "ChangedAt");

                    b.ToTable("sample_analysis_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_sample_analysis_history_new_status", "\"new_status\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_sample_analysis_history_old_status", "\"old_status\" IS NULL OR \"old_status\" IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ChangedById")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("integer")
                        .HasColumnName("old_status");

                    b.Property<long>("SampleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("SampleId", "ChangedAt");

                    b.ToTable("sample_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_sample_history_new_status", "\"new_status\" IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_sample_history_old_status", "\"old_status\" IS NULL OR \"old_status\" IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisParameter", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AnalysisCode", "AnalysisCode")
                        .WithMany("Parameters")
                        .HasForeignKey("AnalysisCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisCode");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisResult", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AnalysisParameter", "AnalysisParameter")
                        .WithMany("Results")
                        .HasForeignKey("AnalysisParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "EnteredBy")
                        .WithMany()
                        .HasForeignKey("EnteredById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.SampleAnalysis", "SampleAnalysis")
                        .WithMany("Results")
                        .HasForeignKey("SampleAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisParameter");

                    b.Navigation("EnteredBy");

                    b.Navigation("SampleAnalysis");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeChunk", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeDocument", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "UploadedBy")
                        .WithMany("UploadedKnowledgeDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeDocumentAnalysisCode", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AnalysisCode", "AnalysisCode")
                        .WithMany("KnowledgeDocumentLinks")
                        .HasForeignKey("AnalysisCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAnalysisTracking.Models.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany("AnalysisCodeLinks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisCode");

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.Sample", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "AssignedTo")
                        .WithMany("AssignedSamples")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "CreatedBy")
                        .WithMany("CreatedSamples")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SampleAnalysisTracking.Models.Location", "Location")
                        .WithMany("Samples")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleAnalysis", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AnalysisCode", "AnalysisCode")
                        .WithMany("SampleAnalyses")
                        .HasForeignKey("AnalysisCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "CompletedBy")
                        .WithMany("CompletedAnalyses")
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "RequestedBy")
                        .WithMany("RequestedAnalyses")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.Sample", "Sample")
                        .WithMany("Analyses")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "StartedBy")
                        .WithMany()
                        .HasForeignKey("StartedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisCode");

                    b.Navigation("CompletedBy");

                    b.Navigation("RequestedBy");

                    b.Navigation("Sample");

                    b.Navigation("StartedBy");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleAnalysisHistory", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.SampleAnalysis", "SampleAnalysis")
                        .WithMany("History")
                        .HasForeignKey("SampleAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("SampleAnalysis");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleHistory", b =>
                {
                    b.HasOne("SampleAnalysisTracking.Models.AppUser", "ChangedBy")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SampleAnalysisTracking.Models.Sample", "Sample")
                        .WithMany("History")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisCode", b =>
                {
                    b.Navigation("KnowledgeDocumentLinks");

                    b.Navigation("Parameters");

                    b.Navigation("SampleAnalyses");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AnalysisParameter", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.AppUser", b =>
                {
                    b.Navigation("AssignedSamples");

                    b.Navigation("CompletedAnalyses");

                    b.Navigation("CreatedSamples");

                    b.Navigation("RequestedAnalyses");

                    b.Navigation("StatusChanges");

                    b.Navigation("UploadedKnowledgeDocuments");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.KnowledgeDocument", b =>
                {
                    b.Navigation("AnalysisCodeLinks");

                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.Location", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.Sample", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("History");
                });

            modelBuilder.Entity("SampleAnalysisTracking.Models.SampleAnalysis", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
